### ISSUE TITLE
Fails to Launch correctly in Epic Games Store (egs)

### ISSUE THREAD

**Issue by s-p-a-r-k-y** [Rfvgyhn/min-ed-launcher#22] opened 2021-04-28 04:03 UTC
Win10 x64 EGS E:D Latest

precisely followed instructions
copy the launch-replacer and the bootstrapper
rename FDev edlaunch.exe
Rename bootstrap

add launch args to EGS E:D 

no go
EGS tries to launch then returns (E:D unlaunched)
no log file generated even when manually created %LOCALAPPDATA%\min-ed-launcher\settings.json
so sad.
is there a possible error in documentation?

**Comment by Rfvgyhn** [comment] 2021-04-28 05:06
There's currently an issue with the latest bootstrapper. Use the bootstrapper from the 3.0 release for now.

Duplicate of #18

**Closed by Rfvgyhn** 2021-04-28 05:06 UTC
